---
language: java
jdk: openjdk11
dist: xenial

git:
  depth: false
  quiet: true

cache:
  directories:
    - ${HOME}/.m2/repository

branches:
  only:
    - master
    - /^SP\/.+$/
    - release
    - /^release\/SP\/.+$/
    - /^MM-.*$/

stages:
  - build
  - release

jobs:
  include:
    - name: "Build"
      stage: build
      before_install: bash _ci/init.sh
      script: bash _ci/build.sh

    - name: "WhiteSource"
      stage: build
      before_install: bash _ci/init.sh
      script: bash _ci/whitesource.sh

    - name: "Release"
      stage: release
      if: branch = release OR branch =~ /^release\/SP\/.+$/
      before_install: bash _ci/init.sh
      script: bash _ci/release.sh
