---
language: java
jdk: openjdk17
dist: xenial

git:
  depth: false
  quiet: true

cache:
  directories:
    - ${HOME}/.m2/repository

before_cache: rm -rf $HOME/.m2/repository/org/gengine

branches:
  only:
    - master
    - /^SP\/.+$/
    - /^HF\/.+$/
    - /^ACS-.*$/
    - /^feature\/.+$/

stages:
  - build
  - release

before_install: bash _ci/init.sh

jobs:
  include:
    - name: "Build"
      stage: build
      script: bash _ci/build.sh

#    - name: "WhiteSource"
#      script: bash _ci/whitesource.sh
    
    - name: "Source Clear Scan (SCA)"  
      before_install: bash _ci/init.sh
      # Run Veracode
      script: travis_wait 30 bash _ci/source_clear.sh

    - name: "Release"
      stage: release
      if: commit_message ~= /\[release\]/ AND branch ~= /^(master|SP\/.+|HF\/.+)$/
      script: bash _ci/release.sh
